pring:
  datasource:
    initialization-mode: always

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true

  h2:
    console:
      enabled: true

  session:
    store-type: jdbc
